name: citra-build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  windows:
    runs-on: windows-2022
    strategy:
      matrix:
        target: ["msvc"]
    env:
      OS: windows
      TARGET: ${{ matrix.target }}
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'
    steps:
      - uses: actions/checkout@v7
        with:
          ref: 70335a7f4d50c092fb04749ac8d45ebeff1814a3
          submodules: recursive
     
      - name: Download Qt
        run: git clone https://github.com/${{ github.repository_owner }}/Qt-Win-Static C:/
        
      - name: Install Visual Studio platform toolset v141
        shell: cmd
        run: |
          "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\setup.exe" modify --quiet --norestart --includeRecommended --installPath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise" --channelId VisualStudio.15.Release --add Microsoft.VisualStudio.Component.VC.v141.x86.x64

      - name: Download Boost
        run: |
          $AllProtocols = [System.Net.SecurityProtocolType]'Tls,Tls11,Tls12'
          [System.Net.ServicePointManager]::SecurityProtocol = $AllProtocols
          
          Invoke-WebRequest -UserAgent curl https://sourceforge.net/projects/boost/files/boost-binaries/1.70.0/boost_1_70_0-msvc-14.1-64.exe/download -OutFile boost_1_70_0-msvc-14.1-64.exe
          .\boost_1_70_0-msvc-14.1-64.exe /sp- /verysilent /suppressmsgboxes /norestart | more
          
      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: 14.16
        if: ${{ matrix.target == 'msvc' }}
        
      - name: Install extra tools (MSVC)
        run: choco install wget
        if: ${{ matrix.target == 'msvc' }}
        
      - name: Build
        shell: cmd
        run: |
          mkdir build && cd build
          cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -G Ninja \
          -DCITRA_ENABLE_COMPATIBILITY_REPORTING=${ENABLE_COMPATIBILITY_REPORTING:-"OFF"} \
          -DCITRA_USE_CCACHE=OFF \
          -DENABLE_COMPATIBILITY_LIST_DOWNLOAD=OFF \
          -DENABLE_FFMPEG_VIDEO_DUMPER=OFF \
          -DENABLE_MF=ON \
          -DENABLE_QT_TRANSLATION=OFF \
          -DENABLE_SDL2=OFF \
          -DOPENSSL_DLL_DIR="C:\Program Files\OpenSSL\bin"
          -DQt5_DIR="C:/Qt/Qt-5.15.19/lib/cmake/Qt5" \
          -DUSE_DISCORD_PRESENCE=OFF \
          ninja
        
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.OS }}-${{ env.TARGET }}
          path: ${{ github.workspace }}\build\Release
          include-hidden-files: true
          if-no-files-found: error
          retention-days: 1
