name: citra-build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  windows:
    runs-on: windows-2022
    strategy:
      matrix:
        target: ["msvc"]
    env:
      OS: windows
      TARGET: ${{ matrix.target }}
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'
    steps:
      - uses: actions/checkout@v7
        with:
          ref: win-7
          submodules: recursive
        
      - name: Download Qt
        run: git clone https://github.com/${{ github.repository_owner }}/Qt-Win-Static C:/Qt
        
      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        if: ${{ matrix.target == 'msvc' }}
        
      - name: Install extra tools (MSVC)
        run: choco install wget
        if: ${{ matrix.target == 'msvc' }}
        
      - name: Build
        shell: cmd
        run: |
          mkdir build && cd build
          cmake .. ^
          -DCMAKE_BUILD_TYPE=Release ^
          -G Ninja ^
          -DCITRA_USE_BUNDLED_QT=OFF ^
          -DCITRA_USE_CCACHE=OFF ^
          -DENABLE_COMPATIBILITY_LIST_DOWNLOAD=OFF ^
          -DENABLE_MF=ON ^
          -DENABLE_SDL2=OFF ^
          -DENABLE_WEB_SERVICE=OFF ^
          -DOPENSSL_DLL_DIR="C:\Program Files\OpenSSL\bin" ^
          -DQt5_DIR="C:/Qt/Qt/Qt-5.15.19/lib/cmake/Qt5"
          ninja
        
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.OS }}-${{ env.TARGET }}
          path: ${{ github.workspace }}\build\Release
          include-hidden-files: true
          if-no-files-found: error
          retention-days: 1
